from . import account_payment
from . import product_pricelist
from . import product_pricing
from . import product_product
from . import product_template
from . import rental_damage_log
from . import res_company
from . import res_config_settings
from . import sale_order
from . import sale_order_line
from . import sale_order_recurrence
from . import stock_lot
